// x402 Payment Configuration
// Generated by THRONE x402-wire script
// Activate: set MCP_WALLET env var to your Base wallet address

export const X402_CONFIG = {
  wallet: process.env.MCP_WALLET || '0xc16F0C96b61411349b38cB0779DD6bf693e8FB2c',
  network: 'base' as const,
  currency: 'USDC',
  enabled: !!(process.env.MCP_WALLET || '0xc16F0C96b61411349b38cB0779DD6bf693e8FB2c' !== 'CONFIGURE_WALLET_ADDRESS'),

  // Per-tool pricing in microUSDC (1 USDC = 1,000,000 microUSDC)
  defaultPrice: 5000,

  // Free tools (health check is always free)
  freeTiers: ['health_check'],
};
